import {
  useAssetUniverseEvaluation,
  useRefreshAssetUniverseEvaluation,
} from '../../api/assetEvaluation';
import { formatRelativeTime } from '../../lib/format';
import type { AssetUniverseEvaluation } from '../../types/api';

/** A titled bulleted list of findings; renders nothing when the list is empty. */
function FindingList({
  title,
  items,
  accent,
}: {
  title: string;
  items: string[];
  accent: string;
}) {
  if (items.length === 0) return null;
  return (
    <div>
      <h4 className="text-sm font-semibold text-slate-900">{title}</h4>
      <ul className="mt-1 flex flex-col gap-1">
        {items.map((item, i) => (
          <li
            key={i}
            className="flex gap-2 text-sm text-slate-600"
          >
            <span aria-hidden="true" className={`mt-1.5 h-1.5 w-1.5 flex-none rounded-full ${accent}`} />
            <span>{item}</span>
          </li>
        ))}
      </ul>
    </div>
  );
}

/**
 * Render the AI evaluation body: the narrative split into paragraphs on blank
 * lines, then the strengths/concerns/suggestions lists.
 */
function EvaluationBody({ evaluation }: { evaluation: AssetUniverseEvaluation }) {
  const paragraphs = evaluation.narrative
    .split(/\n{2,}/)
    .map((p) => p.trim())
    .filter((p) => p.length > 0);

  return (
    <div className="mt-4 flex flex-col gap-4">
      <div className="flex flex-col gap-2">
        {paragraphs.map((paragraph, i) => (
          <p key={i} className="text-sm leading-relaxed text-slate-700">
            {paragraph}
          </p>
        ))}
      </div>
      <FindingList
        title="Strengths"
        items={evaluation.strengths}
        accent="bg-emerald-500"
      />
      <FindingList
        title="Concerns"
        items={evaluation.concerns}
        accent="bg-amber-500"
      />
      <FindingList
        title="Suggestions"
        items={evaluation.suggestions}
        accent="bg-sky-500"
      />
    </div>
  );
}

/**
 * AI assessment of the whole asset universe, shown beneath the composition
 * donuts on the Assets page. The evaluation is lazy-generated by the backend on
 * first load (so an empty cache shows a generating state), can be manually
 * refreshed, and flags itself as outdated when the universe has changed since it
 * was generated.
 */
export function UniverseEvaluationPanel() {
  const query = useAssetUniverseEvaluation();
  const refresh = useRefreshAssetUniverseEvaluation();

  const evaluation = query.data?.evaluation ?? null;
  // The GET lazy-generates when empty, so an initial load may take seconds.
  const generating = query.isLoading || refresh.isPending;

  return (
    <section
      aria-labelledby="universe-evaluation-heading"
      className="rounded-lg border border-slate-200 bg-white p-6 shadow-sm"
    >
      <div className="flex flex-wrap items-start justify-between gap-3">
        <div>
          <h2
            id="universe-evaluation-heading"
            className="text-lg font-semibold text-slate-900"
          >
            Universe evaluation
          </h2>
          <p className="mt-1 text-sm text-slate-500">
            An AI assessment of the asset universe as a whole — diversification,
            concentration, quality, and gaps.
          </p>
        </div>
        <button
          type="button"
          onClick={() => refresh.mutate()}
          disabled={generating}
          aria-busy={refresh.isPending}
          className="inline-flex items-center gap-2 rounded border border-slate-300 px-3 py-2 text-sm font-medium text-slate-700 hover:bg-slate-50 disabled:cursor-not-allowed disabled:opacity-50 focus:outline-none focus-visible:ring-2 focus-visible:ring-emerald-500 focus-visible:ring-offset-1"
        >
          {refresh.isPending && (
            <span
              aria-hidden="true"
              className="h-3.5 w-3.5 rounded-full border-2 border-slate-300 border-t-emerald-500 motion-safe:animate-spin"
            />
          )}
          {refresh.isPending ? 'Refreshing…' : 'Refresh'}
        </button>
      </div>

      {evaluation?.outdated && (
        <p
          role="status"
          className="mt-4 inline-flex items-center gap-2 rounded border border-amber-300 bg-amber-50 px-3 py-2 text-sm text-amber-800"
        >
          <span aria-hidden="true">⚠</span>
          Outdated — the asset universe changed since this was generated. Refresh
          to regenerate.
        </p>
      )}

      {/* ----------------------------------------------------------- GENERATING */}
      {generating && (
        <div
          role="status"
          aria-live="polite"
          className="mt-4 flex items-center gap-2 text-sm text-slate-500"
        >
          <span
            aria-hidden="true"
            className="h-3.5 w-3.5 rounded-full border-2 border-slate-300 border-t-emerald-500 motion-safe:animate-spin"
          />
          Generating the universe evaluation…
        </div>
      )}

      {/* ---------------------------------------------------------------- ERROR */}
      {!generating && (query.isError || refresh.isError) && (
        <p
          role="alert"
          className="mt-4 rounded border border-red-300 bg-red-50 px-3 py-2 text-sm text-red-800"
        >
          Could not generate the universe evaluation. Please try again.
        </p>
      )}

      {/* ------------------------------------------------------------ EVALUATION */}
      {!generating && !query.isError && evaluation && (
        <>
          <EvaluationBody evaluation={evaluation} />
          <p className="mt-4 text-xs text-slate-400">
            Generated {formatRelativeTime(evaluation.generated_at)}
          </p>
        </>
      )}

      {/* ------------------------------------------------------- EMPTY UNIVERSE */}
      {!generating && !query.isError && !refresh.isError && query.data && !evaluation && (
        <p className="mt-4 text-sm text-slate-500">
          Add assets to the universe to generate an evaluation.
        </p>
      )}
    </section>
  );
}

export default UniverseEvaluationPanel;
