"""add recommendation_run

Revision ID: 1caad6f56065
Revises: b2235555b041
Create Date: 2026-09-14 07:41:20.949093

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1caad6f56065'
down_revision: str | Sequence[str] | None = 'b2235555b041'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recommendation_run',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('requested_count', sa.Integer(), nullable=False),
    sa.Column('requested_categories', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=True),
    sa.Column('tool_call_count', sa.Integer(), nullable=False),
    sa.Column('results', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recommendation_run')
    # ### end Alembic commands ###
