"""add portfolios

Revision ID: 4297fafff6af
Revises: 1caad6f56065
Create Date: 2026-09-14 07:57:20.870905

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4297fafff6af'
down_revision: str | Sequence[str] | None = '1caad6f56065'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'portfolios',
        sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
        sa.Column('name', sa.Text(), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('stocks', postgresql.ARRAY(sa.Text()), nullable=False),
        sa.Column('max_allocation_pct', sa.Float(), server_default='1.0', nullable=False),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column(
            'source',
            sa.Enum(
                'recommended', 'manual', 'legacy_backtest', 'legacy_cycle', 'ai_managed',
                name='portfoliosource',
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column(
            'risk_profile',
            sa.Enum(
                'conservative', 'balanced', 'aggressive',
                name='riskprofile',
                native_enum=False,
            ),
            nullable=True,
        ),
        sa.Column('source_run_id', sa.Text(), nullable=True),
        sa.CheckConstraint('array_length(stocks, 1) >= 1', name='stocks_not_empty'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index('idx_portfolios_created_at', 'portfolios', ['created_at'], unique=False)
    op.create_index('idx_portfolios_source', 'portfolios', ['source'], unique=False)
    op.create_index('idx_portfolios_source_run', 'portfolios', ['source_run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_portfolios_source_run', table_name='portfolios')
    op.drop_index('idx_portfolios_source', table_name='portfolios')
    op.drop_index('idx_portfolios_created_at', table_name='portfolios')
    op.drop_table('portfolios')
    # ### end Alembic commands ###
