"""add paper trading tables

Revision ID: 9c73e97d1cf5
Revises: 4297fafff6af
Create Date: 2026-09-14 07:57:57.521299

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9c73e97d1cf5'
down_revision: str | Sequence[str] | None = '4297fafff6af'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'paper_trading_sessions',
        sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
        sa.Column('portfolio_id', sa.UUID(), nullable=False),
        sa.Column('strategy_key', sa.Text(), nullable=False),
        sa.Column(
            'status',
            sa.Enum('active', 'paused', 'stopped', name='sessionstatus', native_enum=False),
            server_default='active',
            nullable=False,
        ),
        sa.Column('allocated_capital', sa.Float(), server_default='100000', nullable=False),
        sa.Column('max_allocation_pct', sa.Float(), server_default='1.0', nullable=False),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('total_trades', sa.Integer(), server_default='0', nullable=False),
        sa.Column('total_pnl', sa.Float(), server_default='0', nullable=False),
        sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            'schedule_mode',
            sa.Enum(
                'MANUAL', 'SCHEDULED', 'DAILY_REBALANCING',
                name='schedulemode',
                native_enum=False,
            ),
            server_default='SCHEDULED',
            nullable=False,
        ),
        sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint(
            'portfolio_id',
            'strategy_key',
            name='uq_paper_trading_sessions_portfolio_strategy',
        ),
    )
    op.create_index(
        op.f('ix_paper_trading_sessions_portfolio_id'),
        'paper_trading_sessions',
        ['portfolio_id'],
        unique=False,
    )
    op.create_table(
        'closed_positions',
        sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
        sa.Column('session_id', sa.UUID(), nullable=False),
        sa.Column('ticker', sa.Text(), nullable=False),
        sa.Column('quantity', sa.Float(), nullable=False),
        sa.Column('entry_price', sa.Float(), nullable=False),
        sa.Column('exit_price', sa.Float(), nullable=False),
        sa.Column('entry_date', sa.DateTime(timezone=True), nullable=False),
        sa.Column('exit_date', sa.DateTime(timezone=True), nullable=False),
        sa.Column('realized_pnl', sa.Float(), nullable=False),
        sa.Column('return_pct', sa.Float(), nullable=False),
        sa.Column('holding_days', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ['session_id'], ['paper_trading_sessions.id'], ondelete='CASCADE'
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        'idx_closed_positions_session',
        'closed_positions',
        ['session_id', 'exit_date'],
        unique=False,
    )
    op.create_table(
        'paper_trades',
        sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
        sa.Column('session_id', sa.UUID(), nullable=False),
        sa.Column('ticker', sa.Text(), nullable=False),
        sa.Column(
            'side',
            sa.Enum('buy', 'sell', name='orderside', native_enum=False),
            nullable=False,
        ),
        sa.Column('quantity', sa.Float(), nullable=False),
        sa.Column('price', sa.Float(), nullable=False),
        sa.Column('notional', sa.Float(), nullable=False),
        sa.Column('signal_type', sa.Text(), nullable=False),
        sa.Column(
            'executed_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column('order_id', sa.Text(), nullable=True),
        sa.Column(
            'order_status',
            sa.Enum(
                'pending', 'submitted', 'filled', 'partially_filled', 'cancelled', 'rejected',
                name='orderstatus',
                native_enum=False,
            ),
            server_default='filled',
            nullable=False,
        ),
        sa.Column('filled_price', sa.Float(), nullable=True),
        sa.Column('filled_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ['session_id'], ['paper_trading_sessions.id'], ondelete='CASCADE'
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index('idx_paper_trades_executed', 'paper_trades', ['executed_at'], unique=False)
    op.create_index('idx_paper_trades_session', 'paper_trades', ['session_id'], unique=False)
    op.create_table(
        'session_runs',
        sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
        sa.Column('session_id', sa.UUID(), nullable=False),
        sa.Column(
            'run_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column('signals_scanned', sa.Integer(), server_default='0', nullable=False),
        sa.Column('signals_actionable', sa.Integer(), server_default='0', nullable=False),
        sa.Column('orders_executed', sa.Integer(), server_default='0', nullable=False),
        sa.Column('orders_skipped', sa.Integer(), server_default='0', nullable=False),
        sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            'status',
            sa.Enum('success', 'failure', name='runstatus', native_enum=False),
            server_default='success',
            nullable=False,
        ),
        sa.Column('run_trigger', sa.Text(), server_default='scheduled', nullable=False),
        sa.Column('duration_ms', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ['session_id'], ['paper_trading_sessions.id'], ondelete='CASCADE'
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        'idx_session_runs_session',
        'session_runs',
        ['session_id', 'run_at'],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_session_runs_session', table_name='session_runs')
    op.drop_table('session_runs')
    op.drop_index('idx_paper_trades_session', table_name='paper_trades')
    op.drop_index('idx_paper_trades_executed', table_name='paper_trades')
    op.drop_table('paper_trades')
    op.drop_index('idx_closed_positions_session', table_name='closed_positions')
    op.drop_table('closed_positions')
    op.drop_index(op.f('ix_paper_trading_sessions_portfolio_id'), table_name='paper_trading_sessions')
    op.drop_table('paper_trading_sessions')
    # ### end Alembic commands ###
