"""add assets and asset_daily_snapshot

Revision ID: b2235555b041
Revises: 2799eb86ac4c
Create Date: 2026-09-14 07:41:07.080354

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b2235555b041'
down_revision: str | Sequence[str] | None = '2799eb86ac4c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('category', sa.Enum('stock', 'crypto', 'etf', 'fund', 'other', name='assetcategory', native_enum=False), nullable=False),
    sa.Column('sector', sa.Enum('technology', 'financial-services', 'healthcare', 'consumer-cyclical', 'consumer-defensive', 'industrials', 'energy', 'basic-materials', 'real-estate', 'utilities', 'communication-services', name='sector', native_enum=False), nullable=True),
    sa.Column('exchange', sa.String(), nullable=True),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('country', sa.Text(), nullable=True),
    sa.Column('city', sa.Text(), nullable=True),
    sa.Column('employees', sa.Integer(), nullable=True),
    sa.Column('website', sa.Text(), nullable=True),
    sa.Column('market_cap_eur', sa.Float(), nullable=True),
    sa.Column('avg_daily_turnover_eur', sa.Float(), nullable=True),
    sa.Column('history_years', sa.Float(), nullable=True),
    sa.Column('is_eligible', sa.Boolean(), nullable=False),
    sa.Column('criteria_results', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assets_country'), 'assets', ['country'], unique=False)
    op.create_index(op.f('ix_assets_ticker'), 'assets', ['ticker'], unique=True)
    op.create_table('asset_daily_snapshot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('current_price', sa.Float(), nullable=True),
    sa.Column('previous_close', sa.Float(), nullable=True),
    sa.Column('short_description', sa.Text(), nullable=True),
    sa.Column('volume', sa.BigInteger(), nullable=True),
    sa.Column('avg_volume', sa.BigInteger(), nullable=True),
    sa.Column('price_history', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_id', 'snapshot_date', name='uq_asset_daily_snapshot_asset_date')
    )
    op.create_index(op.f('ix_asset_daily_snapshot_asset_id'), 'asset_daily_snapshot', ['asset_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_asset_daily_snapshot_asset_id'), table_name='asset_daily_snapshot')
    op.drop_table('asset_daily_snapshot')
    op.drop_index(op.f('ix_assets_ticker'), table_name='assets')
    op.drop_index(op.f('ix_assets_country'), table_name='assets')
    op.drop_table('assets')
    # ### end Alembic commands ###
