"""add ai portfolio events

Revision ID: de5a2bf36170
Revises: 9c73e97d1cf5
Create Date: 2026-09-14 08:17:05.953193

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'de5a2bf36170'
down_revision: str | Sequence[str] | None = '9c73e97d1cf5'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_portfolio_events',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('portfolio_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.Enum('build', 'rebalance', name='eventtype', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('queued', 'running', 'succeeded', 'partial', 'failed', 'skipped', name='eventstatus', native_enum=False), server_default='queued', nullable=False),
    sa.Column('request_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('result_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('actions_taken', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['paper_trading_sessions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ai_portfolio_events_session', 'ai_portfolio_events', ['session_id', 'created_at'], unique=False)
    op.create_index('idx_ai_portfolio_events_status', 'ai_portfolio_events', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_ai_portfolio_events_status', table_name='ai_portfolio_events')
    op.drop_index('idx_ai_portfolio_events_session', table_name='ai_portfolio_events')
    op.drop_table('ai_portfolio_events')
    # ### end Alembic commands ###
